perlin-network/noise

- README.md
- examples/basic/example_test.go
- examples/chat/main.go
- examples/cluster_benchmark/main.go
- examples/getting_started/main.go
- examples/local_benchmark/receiver/main.go
- examples/local_benchmark/sender/main.go
- examples/proxy/proxy_test.go
- examples/stream/main.go
- examples/topologies/topologies.go
- network/address_test.go
- network/backoff/plugin_test.go
- network/builder.go
- network/builder_test.go
- network/nat/plugin.go
- network/network.go
- network/plugin_test.go
- network/ring_buffer.go
- network/ring_buffer_test.go
- network/stream.go
- network/utils.go
- network/utils_test.go
network/builders: Removed package.
network: Added network.Builder.
examples: Made all examples use network.Builder.
readme: Updated readme to use network.Builder.
Makes it easier to test the `network/` package.
> network/builders: Removed package and moved it to network/builder.go.

- .codecov.yml
- seems like mostly generated external assembly code: crypto/ed25519/internal/edwards25519
- this restores coverage from 29% -> 55%
> Ignore Edwards25519 from coverage.

- .travis.yml
- README.md
- go.mod
- network/network.go
- network/stream.go
- looks like July 19th version of vgo broke the CI, so locked in the version before that in travis
- adjusted some of the logging, doesn't glog error when the message is empty now
> Fix CI, clean up logs.

- README.md
Cleaned up a few typos and reformatted the README to stick to a 80 chars max line length.
> README: clean-up, typos and stick to 80 chars per line

- callbacks/reduce.go
- cipher/aead/crypto.go
- cipher/aead/mod.go
- cipher/aead/mod_test.go
- examples/benchmark/main.go
- examples/chat/main.go
- examples/e2e/e2e_test.go
- node.go
- params.go
- peer.go
- protocol/mod.go
- skademlia/mod.go
- skademlia/rpc.go
- skademlia/table_test.go
- transport/tcp.go
There is a race condition that I and @losfair have been trying to fix for awhile now.
The race condition goes as follows:
1) I send aead.ACK.
2) Peer sends aead.ACK.
3) Peer receives aead.ACK and sends skademlia.Ping, but we haven't atomically locked all reads yet.
Thus, we receive skademlia.Ping encrypted (as after aead.ACK is received, we enable AEAD encryption), and are unable to decode it as we have not enabled AEAD as of yet.
To reproduce, `cd` to `examples/e2e` and run `go test -v -count=100`, and you will see disconnections/failure to read encrypted messages.
> Fix race condition over the network for AEAD.

- node_test.go
- peer.go
- peer_test.go
- protocol/mod_test.go
Also add a test in `peer_test.go` to check for this condition.
Furthermore, it seem fixing the bug causing two of the tests (one in `node_test.go`, one in `protocol/mod_test.go`) to fail because the two tests were depending on the bug.
So, I've updated the tests.
> Fix a bug that happens when peer's connection is closed by the dialler.

- skademlia/binary.go
- skademlia/binary_test.go
- skademlia/table.go
The bug is only triggered if all the bytes are zero where it'll return wrong result if the bytes are all zero.
> Fix minor bug in skademlia.prefixLen(b []byte).

- skademlia/table.go
- skademlia/table_test.go
If node is disconnected it's id is not getting deleted from skademlia table.
Then if same node (same public key) is connecting again its getting update in table, but if it has different address it won't get updated.
Added tests to reproduce + fix
https://github.com/perlin-network/wavelet/issues/227
> Allow addresses of nodes in S/Kademlia routing table to be dynamically changed.

- skademlia/client.go
Store a list of peer addresses which we are unable to dial, to fail more quickly when dialing peers frequently
> Add a global peer blacklist

- skademlia/client.go
Use a random delay to increase the odds that two peers are not blacklisting each other
> Use a random delay when blacklisting

- skademlia/client.go
- skademlia/client_test.go
- skademlia/protocol.go
- skademlia/protocol_test.go
Only add the peer to the routing table after verifying that it is reachable.   Additionally, this changeset improves dialing such that it does not block with the peers lock held.  Instead, dialing is done asynchronously and when the link first becomes ready it is pinged.
> Improve client/protocol state machine

- skademlia/client_test.go
- skademlia/protocol.go
Currently, there's a data race on noise.Info because it's modified on another Goroutine after dialling the peer.
This PR fixes the data race by move the modification to the original Goroutine.
This means the we set the ID first before starting another Goroutine to dial the peer and if the dial successful, add it to the table.
This PR also reworks the eviction unit test and minor cleans code.
> Fix a data race in noise.Info

- skademlia/table.go
Currently, there's a data race on skademlia.ID when the address of the ID is updated in case the its address is different.
Since skademlia.ID should be immutable, the solution should be to remove the ID and add it again.
This PR implements the solution.
> Fix a data race by re-adding the ID if its address is different

- skademlia/table.go
The PR adds expanded comments on why the ID is re-added if it's address has changed to provide more context.
> Add comments to explain why ID may be re-added

- skademlia/protocol.go
Problem is that after restarting a node it much longer than expected take time to connect.
_node1 is always running, node2 is one which is reconnecting_
After node2 is disconnecting, `connLoop` constantly retries this connection up until it either will be READY again or after 30*3s will pass.
What happens if node2 is getting started again - node2 is dialing node1, grpc dial is successful, credentials check as well, so we store this connection to peers and start `connLoop` goroutine. Meanwhile node1 is trying to create its client back to node2 in async way, but it fails, since it ALREADY HAS connection to it in `peers` map and its broken (its in transient failure state and did not yet recover). So node1 is closing new connection from node2. Then somewhere around same time node2 after …
> Don't close incoming connection on failed dial back.

- cipher/cipher.go
This PR removes the check which panics if the CPU does not support AES-NI instructions. Without AES-NI support, the AES implementation [provided by Go](https://golang.org/pkg/crypto/aes) is [not constant-time](https://github.com/golang/go/issues/16821/).
This change is done to allow noise to work on CPU which does not support AES-NI instructions, like Raspberry pi.
> Allow noise to work if CPU does not support AES-NI

- examples/chat/main.go
- skademlia/client.go
Currently, `ClosestPeers()` returns a list of connections, without their IDs. What if we also want connection ID ?
The only way get both ID and connection is to do it yourself, by manually calling `ClosestPeerIDs` and call `Dial` on each ID.
This PR introduces a type that wraps connection and ID, to be returned by `ClosestPeers()`.
> Implement a type to wrap conn and id, returned by ClosestPeers

- callbacks/sequential.go
On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.
Fixes #264
> Align atomic values

- kademlia/protocol_test.go
- map.go
- node_options_test.go
map: have eviction policy of connection pool behave as a lru
kademlia/test: assert that all inbound connections to leader node are ready
node/opts/test: have quickcheck run only 10 iterations per option to reduce testing time
> Implement LRU eviction policy for connection pool, and reduce flakiness of Kademlia test.

- client.go
- conn.go
- node_test.go
This removes the need for there being one extraneous goroutine per connection and removes the need for keeping track of an idle timeout timer per *noise.Client.
> client, conn: remove idle timeout goroutine and use net.Conn read/write deadlines instead

- client.go
- kademlia/protocol.go
- kademlia/table.go
- keys.go
- mod.go
- node.go
Few security considerations were implemented alongside helper methods for dealing with cryptographic keys. After benchmarking with software written on top of Noise, a switch from using a pre-allocated slice to a linked list was done for representing Kademlia routing tables.
```
client, node: have OnMessageSent called less frequently
kademlia/protocol, kademlia/table: switch from using a slice to a linked list for representing the routing table to make id updates more efficient, and add Last() to get the last entry of a bucket near a target public key
client, node, keys: add LoadKeysFromHex to load a private key from hex, add Signature type to represent cryptographic signatures, and add UnmarshalSignature which uses unsafe hackery to convert a byte slice into a signature
client: add …
```
> Extends cryptographic keys API, reduce frequency of OnMessageSent being called, improve cache locality of Kademlia routing table.

- README.md
- aead.go
- client.go
- go.mod
- go.sum
Shaved away an allocation in `encryptAEAD`, and switched to using `sync.Cond` for reducing lock contention in `client.go` when sending large amounts of messages with high flush latency.
> Reduce AEAD allocations, and switched to using sync.Cond for reducing lock contention in clients.
